#!/bin/csh -f

#alias cmake cmake3
# library from http://proj-clhep.web.cern.ch/proj-clhep/

# Additional settings at the top of get_coptions
source get_coptions env

# Options
set name     = AmpTools
set release  = `./get_coptions release`
set repo     = https://downloads.sourceforge.net/project/amptools
set version  = $AMPTOOLS_VERSION
set filename =  AmpTools"_v"$AMPTOOLS_VERSION".tgz"
set arch     = `./get_coptions arch`
set opt      = `./get_coptions copt`
set cmakev   = `./get_coptions cmakev | awk '{print $1}'`

# Exit if cmake is not >= 3.3
if($cmakev != "OK") then
	./get_coptions cmakev
	exit
endif


# Write options on screen
./get_coptions log $name $version $filename $release $arch $opt


# Checking if the OS is 32 bit. 
set oarch = ""
if($arch == "32") then
	set oarch = '-DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 -DCPACK_SYSTEM_NAME=$OSRELEASE'
endif
echo " > Special Compilation Options: " $oarch 
echo

if($1 == "src"|| $1 == "make" || $1 == "fixconfig") goto $1

# Source Build
src:
	# Getting source file
	echo " > Installing AmpTools version "$version" - release "$release". Getting and unpacking" $filename"..."
	rm -rf   $AMPTOOLS
	mkdir -p $AMPTOOLS
	cd $AMPTOOLS/../
	mkdir src
	cd src
	wget     $repo/$filename
	echo Unpacking $filename
	tar -xvf     $filename >& /dev/null
	mv AmpTools/AmpTools/* $AMPTOOLS
	mv AmpTools/Tutorials $AMPTOOLS/../
	mv AmpTools/AmpPlotter $AMPTOOLS/../
	rm -rf $AMPTOOLS/../src
if($1 == "src") exit

# make
make:
	# Configuring and Compiling
	echo " > Configuring and compiling AmpTools source (log will be in "\$OPENMPI/"make_log)..."
	cd $AMPTOOLS
	if(! $?OPENMPI) then
	    echo "MPI not enabled"
	    make $opt    >> $AMPTOOLS/make_log
	else
	    echo "MPI enabled"
	    make $opt MPI=1 >> $AMPTOOLS/make_log
	endif
	echo " > Configuring and compiling AmpPlotter source (log will be in "\$OPENMPI/"make_log)..."
	cd $AMPPLOTTER
	    make $opt 

if($1 == "make") exit





# Done!
echo done
echo




# Warning: on mac I get errors on the clhep script
# To fix:
# use the full name of this script to get the current path
# configpath=`dirname ${0}`
# binpath=${configpath}
fixconfig:
if(`uname` == "Darwin") then
	grep -B100 "# use the full name of this script to get the current path" $CLHEP_BASE_DIR/bin/clhep-config  > tmp
	echo 'configpath=`dirname ${0}`'                                                                         >> tmp
	echo 'binpath=${configpath}'                                                                             >> tmp
	grep -A200 "# OK - now we have to strip the trailing " $CLHEP_BASE_DIR/bin/clhep-config                  >> tmp
	mv tmp $CLHEP_BASE_DIR/bin/clhep-config
	chmod a+x  $CLHEP_BASE_DIR/bin/clhep-config
endif
if($1 == "fixconfig") exit




































